version: '3.7'
services:
  app:
    depends_on:
      - mongo
    tmpfs: /root/nemp3/tmp
    volumes:
      - type: bind
        source: .
        target: /root/nemp3

  mongo:
    image: mongo
    ports:
      - '27017:27017'
