version: "3.7"
services:
  app:
    build:
      context: .
      target: nemp3
    command: /usr/bin/node /root/nemp3/index.js
    container_name: "nemp3-server"
    depends_on:
      - rabbit
      - mongo
    env_file: prod.env
    networks:
      - internal
    ports:
      - "8083:8083"
    restart: always
    tmpfs: /root/nemp3/tmp

  mongo:
    command: mongod --auth
    container_name: mongo
    image: mongo
    networks:
      internal:
        aliases:
          - mongo
    ports:
      - "27017"
    restart: always
    volumes:
      - data-volume:/data/db

  rabbit:
    container_name: rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    expose:
      - "5672"
    hostname: rabbit
    image: rabbitmq:3.8.2-management
    networks:
      internal:
        aliases:
          - rabbit
    ports:
      - "15672:15672"
    restart: always

networks:
  internal:
    driver: bridge

volumes:
  data-volume:
