version: '3.7'
services:
  app:
    build:
      context: .
      target: nemp3-dev
    command: >
      sh -c
      "cd /root/nemp3/
      && npm i
      && /usr/bin/nodemon --ignore client -L /root/nemp3/index.js"
    container_name: 'nemp3-server-dev'
    env_file: dev.env
    ports:
      - '8083:8083'
    restart: 'no'
  rabbit:
    container_name: rabbit
    hostname: nemp3-rabbit
    image: rabbitmq:3.8.2-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - '5672'
      - '15672:15672'
